title: Alicia Pérez Jiménez
logo: "/images/2018-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist @ <a href="https://stylesage.co/">StyleSage</a> <br>
  Co-organizer @ <a href="https://www.meetup.com/es-ES/PyLadiesMadrid/">PyLadies Madrid</a>
  <br><br>
  <a href="https://www.linkedin.com/in/aliciapj/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
